# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oQ8Onyl-tRGUt0vIzbzLLVQOid_5wrqv
"""

from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target
df.head()

df.shape

df.columns
df.info()

df.describe()

df['species'].value_counts()

import matplotlib.pyplot as plt

plt.scatter(df['sepal length (cm)'], df['petal length (cm)'])
plt.xlabel("Sepal Length")
plt.ylabel("Petal Length")
plt.show()

df[df['species'] == 0].head()
df[df['species'] == 1].head()

df.corr()

df.sort_values(by='petal length (cm)').head()